language: java
jdk:
  - oraclejdk8

sudo: false

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  - NODE_VERSION=8.5.0
before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
  - bower -v
  - gulp -v
  - java -version
install:
  - npm install
script:
  - ./mvnw clean
  - ./mvnw test
