version: '2'
services:
    saotome-app:
        image: saotome
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://saotome-mysql:3306/saotome?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    saotome-mysql:
        extends:
            file: mysql.yml
            service: saotome-mysql
